name: 🚀 Deploy Laravel to Hostinger via SSH

on:
  push:
    branches:
      - homolog

jobs:
  deploy:
    name: 🎉 Deploy to Hostinger
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout latest code
        uses: actions/checkout@v4

      - name: 🛠️ Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HOMOLOG_SSH_KEY }}" > ~/.ssh/CaiqueJar
          chmod 600 ~/.ssh/CaiqueJar
          ssh-keyscan -p 65002 46.202.145.2 >> ~/.ssh/known_hosts

      - name: 🚀 Run deployment script on server
        run: |
            ssh -p 65002 -i ~/.ssh/CaiqueJar u182216510@46.202.145.2 << 'EOF'
                cd /home/u182216510/domains/mediumaquamarine-seahorse-148124.hostingersite.com/public_html
                git pull origin homolog
                cp .env.homolog .env
                php composer.phar install --no-interaction --prefer-dist --optimize-autoloader
                php artisan migrate --force
                php artisan config:cache
                php artisan route:cache
            EOF
